### ISSUE TITLE
AttributeError: 'TSocket' object has no attribute 'is_open'

### ISSUE THREAD

**Issue by szelenka** [cloudera/thrift_sasl#12]
The removal of isOpen breaks backwards compatibility with older versions of Thrift, it will throw errors at is_open:

`/home/datascience/conda/lib/python3.6/site-packages/thrift_sasl/__init__.py in open(self)
     65 
     66   def open(self):
---> 67     if not self._trans.is_open():
     68       self._trans.open()
     69 

AttributeError: 'TSocket' object has no attribute 'is_open'
`
This is linked to this commit:
https://github.com/cloudera/thrift_sasl/commit/892ead18c163eec873fab68d7409053f50a8f0df

Reverting back to an older tag (v0.3.0) seems to get around this problem.

**Comment by yanchvlad** [comment]
I have similar problem:

     65 
     66   def open(self):
---> 67     if not self._trans.isOpen():
     68       self._trans.open()
     69 

AttributeError: 'TSocket' object has no attribute 'isOpen'

**Comment by gregrahn** [comment]
@szelenka @yanchvlad - I merged in PR #13 so could you see if that fixes your issues?

**Comment by gglanzani** [comment]
@gregrahn Can you maybe tag a new release? 0.3.1 maybe?

**Comment by gregrahn** [comment]
@gglanzani That's the plan given no problems =)

**Comment by anilpai** [comment]
The PR #13 started to break things.. When will this bug be fixed ? I am planning to revert back to penultimate commit.

**Comment by ccphillippi** [comment]
@anilpai are you using both `thrift` and `thriftpy`? Possible to show the stack trace? The current implementation after #13 trys for `thrift`'s `isOpen`, otherwise uses `thriftpy`'s `is_open`. 

My understanding of the issue is that the `TSocket` has different implementations based on whether you're using `thrift`, `thriftpy` or something else.

**Comment by mlboy** [comment]
need a new tag 0.3.1 ,why not make a new tag? @gregrahn

**Comment by biocar2001** [comment]
hi,

Here there is a problem. When I am working with the connection of impyla with impala and kerberos, with the version of thrift-sasl-0.3.0 I get the error:

AttributeError: 'TSocket' object has no attribute 'isOpen'

If I upgrade to 0.2.1 everything is OK, but I have other problem, the connection with hive and kerberos doesnt work and I need the version 0.3.0 because in the previous version tell me:

method readall doesnt exist.

What Can I do for both versions works?
Thanks in advance

**Comment by svrakitin** [comment]
@gregrahn Any update on v0.3.1?

**Comment by yhOliver** [comment]
@gregrahn Any update on v0.3.1?
