### ISSUE TITLE
the new version 0.4.1 will cause pandas read_sql() stuck

### ISSUE THREAD

**Issue by pokerc** [cloudera/thrift_sasl#22]
**import pandas as pd
hql="select * from test_tb"
pd.read_sql(hql, hive_conn)**

the code above will stuck in read_sql step.
and at the version 0.3.0 it will be ok

**Comment by Lordshinjo** [comment]
Indeed since #10, and in particular the changes from `_trans.readAll()` to `_trans.read()`, queries can randomly hang.

The issue is that `read()` makes no attempt to read the full requested data (e.g. `TSocket` only does a single `socket.recv()` call), while `readAll()` does.
As a consequence, if a frame does not fit in a single `read()` call, the frame is not fully read. Any subsequent calls will then return garbage data, which may hang on the client side when trying to read a binary with a stupidly large size, or just break altogether.

I just created #23 to fix this.
